Add markdown message
nonebot/adapter-console pull request #2
Opened 2022-08-30 02:44 UTC by Melodyknit

2022-08-30 02:59 UTC, yanyongyu commented
pre-commit.ci run

2022-08-30 03:44 UTC, yanyongyu requested changes

2022-08-30 03:44 UTC, yanyongyu commented on nonebot/adapters/console/terminal/app.py
> +        ensure_future(wait(create_task(on()) for on in self.on))
```suggestion
        create_task(wait(create_task(on()) for on in self.on))
```

2022-08-30 03:44 UTC, yanyongyu commented on nonebot/adapters/console/terminal/app.py
> +            logger.info("%s: %s" % (event.user_info.nickname, message))
```suggestion
            logger.info(f"{event.user_info.nickname}: {message}")
```

2022-08-30 03:44 UTC, yanyongyu commented on pyproject.toml
> +    "textual==0.1.18"
这里又是咋回事，textual怎么不再dependencies里

2022-08-30 04:37 UTC, Melodyknit commented on pyproject.toml
> +    "textual==0.1.18"
啊，抱歉

2022-08-31 02:11 UTC, yanyongyu commented
虽然但是，你的`poetry.lock`呢，怎么没更新

2022-09-01 02:08 UTC, yanyongyu approved these changes

2022-09-01 02:09 UTC, merged